homepage:
    pattern: /
    defaults: { _controller: SensioHangmanBundle:Game:index }

SensioHangmanBundle:
    resource: "@SensioHangmanBundle/Controller/"
    type: annotation
    prefix: /

login_check:
  pattern: /auth
  defaults: {_method:POST}

logout:
  pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
