homepage:
    pattern: /
    defaults: { _controller: SensioHangmanBundle:Game:index }

SensioHangmanBundle:
    resource: "@SensioHangmanBundle/Controller/"
    type: annotation
    prefix: /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
