security:
    encoders:
        Sensio\Bundle\HangmanBundle\Entity\Player: sha512

    providers:
        players:
            entity: { class: SensioHangmanBundle:Player, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        game:
            pattern:    ^/
            anonymous: ~
            form_login:
              login_path: login
              check_path: login_check
              default_target_path: hangman_game
            logout:
              path: logout
              target: login

    access_control:
        - { path: ^/game, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/roles, roles: IS_AUTHENTICATED_ANONYMOUSLY }
