<?php

namespace Sensio\Bundle\HangmanBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GameController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sensio\Bundle\HangmanBundle\Controller\GameController();
        return $instance;
    }
}
